### ISSUE TITLE
Question in GIST Feature Extraction part

### ISSUE THREAD

**Issue by cherrypiecoco** [amr4i/EmotionDetection#10]
Hi, I'm having a little trouble with running the code segment below (related to GIST Feature Extraction). My Window commands window returns "make' is not recognized as an internal or external command, operable program or batch file." Is there something that I'm missing here? Sorry, I'm very new to this. Your help is greatly appreciated.

GIST Feature Extraction:
Run the code segment:
 	cd GIST 
 	make IMAGEPATH=<path_to_directory_containing_all_images>

**Comment by cherrypiecoco** [comment]
No worries! I was able to handle this :)

**Comment by Divyaa2018** [comment]
How did you solve this??I am facing the same issue .

**Comment by cherrypiecoco** [comment]
I thought I solved it and closed the question, but actually it didn't work.
haha...If you happen to find the solution, please let me know.

**Comment by xinli2008** [comment]
hello,have you sloved the problem?And have you run the code successfully? @ @cherrypiecoco
