### ISSUE TITLE
Where to get the semantic encoder and decoder weights

### ISSUE THREAD

**Issue by cswin** [amr4i/EmotionDetection#6]
Where can I get the semantic encoder and decoder weights?

**Comment by asadabbas09** [comment]
download the pre-trained weights from http://sceneparsing.csail.mit.edu/model/pytorch/

More info at: https://github.com/CSAILVision/semantic-segmentation-pytorch

**Comment by cswin** [comment]
Thank you.  
Could you give the sample of how to run the code?   I cannot match the code with the weights.  
 
    parser.add_argument('--arch_encoder', default='resnet50_dilated16',
                        help="architecture of net_encoder")
    parser.add_argument('--arch_decoder', default='psp_bilinear',
                        help="architecture of net_decoder")
    parser.add_argument('--fc_dim', default=2048, type=int,
                        help='number of features between encoder and decoder')

    # Path related arguments
    parser.add_argument('--weights_encoder', default='./model/baseline-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth')
    parser.add_argument('--weights_decoder', default='./model/baseline-resnet50dilated-ppm_deepsup/decoder_epoch_20.pth')

**Comment by cswin** [comment]
@asadabbas09 Thanks for your help.  I used another network code in tensroflow to achieve the semantic features successfully.

**Comment by annahung31** [comment]
Hi dear @cswin , may I ask which network code you used instead?
Thanks a million!!
