### ISSUE TITLE
Color Features

### ISSUE THREAD

**Issue by asadabbas09** [amr4i/EmotionDetection#7]
Thanks for sharing the code.

I have trained the model and noticed some differences from the original implementation, but overall everything works fine.

However, I couldn't find anywhere if you have incorporated "Color Features" into the input vector?

GIST: 512
VGG:1000
LBP: 59
SEM: 150

Equals 1721 dim input vector. So have you left out colour features? Because I could not get results compared to the original paper, I'm not sure if this is because of leaving out colour features.

**Comment by cswin** [comment]
GIST should be 320-dimensional vector? according to the paper  

Color features have 59 dimensions

**Comment by asadabbas09** [comment]
@cswin yes, but this code apparently extract 512-dimensional gist features.

have you extracted colour features yourself? I'm not sure how to proceed

**Comment by amr4i** [comment]
I did not implement color features at that time, but that didn't seem to affect the results considerably. Also, GIST is 512 dimensional in the standard form, so I used that. Not sure why/how the authors propose the other size.  Hope this helps!

**Comment by asadabbas09** [comment]
@amr4i I couldn't achieve the results reported in the original paper. I get pretty similar results for using self-extracted features or using the extracted features provided by authors in their released dataset. Thanks for your help.

**Comment by cswin** [comment]
@amr4i Thanks for your help.

**Comment by asadabbas09** [comment]
@cswin have you extracted colour features? How do you calculate 59 dimensions of colour for an image?

**Comment by cswin** [comment]
I did not extract color features yet.

The paper did not tell the details of this.

I am still working on the three types of features for training.
