### ISSUE TITLE
Why labels.append(file_label/100.0) ?

### ISSUE THREAD

**Issue by cswin** [amr4i/EmotionDetection#8]
Why is it label /100.0 in the function get_features included in EmotionDetection/extract_features.py?

For example, if the label value represents the Arousal score, which is equal to 2.84,  should we set the label to be exact 2.84?  or normalized value (2.84-1)/(9-1) ?

**Comment by asadabbas09** [comment]
I think it is just for normalization. Authors did not do any kind of normalization of output labels in their work. So you can just take 2.84 without normalizing it.

**Comment by cswin** [comment]
@asadabbas09 Thank you.  Did you get a similar result for loss error without normalizing the labels?
